language: node_js
node_js: "6.3.1"
cache:
  directories:
    - node_modules
    - vendor/bundle

install:
  - rvm install 2.3.1 --install --binary --fuzzy
  - npm install
  - cd web-console && bundle install --path $TRAVIS_BUILD_DIR/vendor/bundle -j4
  - cd $TRAVIS_BUILD_DIR

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - cd web-console/test/dummy && bundle exec rackup -q --host 0.0.0.0 --port 19292 &
  - cd $TRAVIS_BUILD_DIR
  - sleep 10
  - mkdir tmp
  - npm test
  - ls tmp/
