language: nodejs

node_js: "6.3.1"
rvm: "2.3.1"

install:
  - pushd web-console && bundle install -j4 && popd

script:
  - pushd web-console/test/dummy && bundle exec rackup --host localhost --port 19292 &; popd
  - sleep 10
  - mkdir tmp
  - npm test
  - ls tmp/
