language: node_js

node_js: "6.3.1"

install:
  - rvm install 2.3.1 --install --binary --fuzzy
  - npm install
  - cd web-console && bundle install -j4
  - cd $TRAVIS_BUILD_DIR

script:
  - cd web-console/test/dummy && bundle exec rackup --host localhost --port 19292 &
  - cd $TRAVIS_BUILD_DIR
  - sleep 10
  - mkdir tmp
  - npm test
  - ls tmp/
