language: node_js
node_js: 6.3.1
cache:
  directories:
    - node_modules
    - vendor/bundle

install:
  - env
  - mkdir tmp
  - rvm install 2.3.1 --install --binary --fuzzy
  - npm install
  - cd web-console && bundle install --path $TRAVIS_BUILD_DIR/vendor/bundle -j4
  - cd $TRAVIS_BUILD_DIR

before_script:
  - source ./script/xvfb.source.bash

script:
  - bash ./script/dummy.bash
  - sleep 7
  - npm test
  - ls tmp/
  - bash ./script/upload.bash
