language: node_js
node_js: 6.3.1
cache:
  directories:
    - node_modules
    - vendor/bundle

install:
  - rvm install 2.3.1 --install --binary --fuzzy
  - npm install
  - cd web-console && bundle install --path $TRAVIS_BUILD_DIR/vendor/bundle -j4
  - cd $TRAVIS_BUILD_DIR

before_script:
  - source ./script/xvfb.source.bash

script:
  - mkdir tmp
  - bash ./script/dummy.bash
  - sleep 3
  - npm test autocomplete
  - npm test suggest
  - "for x in tmp/*.gif; do echo upload: $x; bash ./script/upload.bash $x; done"
